name: aimesig_chat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3      # Linux + Windows SQLite via FFI


  # Utilities
  path: ^1.9.0
  uuid: ^4.4.0
  crypto: ^3.0.3                  # SHA-256 for stable device ID
  shared_preferences: ^2.2.3

  # Network info (optional, for display only)
  network_info_plus: ^5.0.3
  connectivity_plus: ^6.0.3

  # Permissions (mobile only — safe to include on desktop, just unused)
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true