// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAjPdovO9256fOWv9M3UA-9VI6Ao4wY90',
    appId: '1:511798348683:web:f4bfc3548a3a8b96b53d8e',
    messagingSenderId: '511798348683',
    projectId: 'aimapp-5cfbf',
    authDomain: 'aimapp-5cfbf.firebaseapp.com',
    storageBucket: 'aimapp-5cfbf.firebasestorage.app',
    measurementId: 'G-WYX8JLMK7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMqH5VCWRvzLw1SXo0ZV_LULAhGQ_6Oos',
    appId: '1:511798348683:android:83620a4b460ed796b53d8e',
    messagingSenderId: '511798348683',
    projectId: 'aimapp-5cfbf',
    storageBucket: 'aimapp-5cfbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQh9-TPDt0KAoqQd8Zq3UFBWAIE7vi7Ss',
    appId: '1:511798348683:ios:eaada4528e693343b53d8e',
    messagingSenderId: '511798348683',
    projectId: 'aimapp-5cfbf',
    storageBucket: 'aimapp-5cfbf.firebasestorage.app',
    iosBundleId: 'com.aimesig.aimapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQh9-TPDt0KAoqQd8Zq3UFBWAIE7vi7Ss',
    appId: '1:511798348683:ios:92dc54ac11086382b53d8e',
    messagingSenderId: '511798348683',
    projectId: 'aimapp-5cfbf',
    storageBucket: 'aimapp-5cfbf.firebasestorage.app',
    iosBundleId: 'com.example.aimesigChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAjPdovO9256fOWv9M3UA-9VI6Ao4wY90',
    appId: '1:511798348683:web:c5ed8fce10e8946eb53d8e',
    messagingSenderId: '511798348683',
    projectId: 'aimapp-5cfbf',
    authDomain: 'aimapp-5cfbf.firebaseapp.com',
    storageBucket: 'aimapp-5cfbf.firebasestorage.app',
    measurementId: 'G-5DW0WQCY80',
  );
}
